spectaql:
  logoFile: ./logo.png
  faviconFile: ./favicon.ico
  displayAllServers: true
  targetDir: ./docs
introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./src/schema.gql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true


info:
  title: GraphQL API Book CMS Reference
  description: Welcome to the party!
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    email: yurstan@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-introItems:
    - title: Important thing 1
      description: Some important stuff we wanted you to know. Supports `markdown`

servers:
  - url: http://localhost:3000/graphql
    description: Staging
  - url: http://localhost:3000/graphql
    description: Production
    production: true
    headers:
      - name: Authorization
        example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOjEsImlhdCI6MTcxNzk5NzkxNywiZXhwIjoxNzE4MDg0MzE3fQ.j9W9e3eCh2-etItNQdqXK7bqfMwC7h-aJPOkFXooEf0
        comment: Your foo from bar
    # Example queries and mutations to include in the documentation

hooks:
  preBuild: echo "Preparing to build documentation..."
  postBuild: echo "Documentation build complete."
